apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: k4va6wzxl-python
  janus-idp.io/tekton: k4va6wzxl-python
  backstage.io/kubernetes-id: k4va6wzxl-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: k4va6wzxl-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
